from os import system
from colorama import Fore, init
init()

def autor():
    system("cls")
    print("\n          Autor: Yonatan Henao R, Versión 1.0.0")

def banner():
    print("")
    print(Fore.LIGHTYELLOW_EX + "          dBBBBb dBBBBBb     dBBBBb  dBBBB.dBBBBP     ")
    print("             dBP      BB        dBP dBP.BPBP          ")
    print("        dBP dBP   dBP BB   dBP dBP dBP.BP `BBBBb      ")
    print("       dBP dBP   dBP  BB  dBP dBP dBP.BP     dBP      ")
    print("      dBBBBBP   dBBBBBBB dBBBBBP dBBBBP dBBBBP'       ")
    print("                                                 ")
    print(Fore.LIGHTBLUE_EX + "                    dBBBBb  dBBBP                     ")
    print("                       dBP                            ")
    print("                  dBP dBP dBBP                        ")
    print("                 dBP dBP dBP                          ")
    print("                dBBBBBP dBBBBP                        ")
    print("                                                 ")
    print(Fore.LIGHTRED_EX + "       dBBBBBb dBBBBBP dBBBBBb   dBBBBBb              ")
    print("            BB              BB       dBP              ")
    print("        dBP BB   dBP    dBP BB   dBBBBK               ")
    print("       dBP  BB  dBP    dBP  BB  dBP  BB               ")
    print("      dBBBBBBB dBBBBP dBBBBBBB dBP  dB'               " + Fore.RESET)

def dadosImg():
    print("                                  ,.................        ")
    print("                                 ,.. ." + Fore.LIGHTMAGENTA_EX + "&&&&" + Fore.RESET + "......" + Fore.LIGHTMAGENTA_EX + "&&&" + Fore.RESET + "..       ")
    print("                               ,,&,..................,      ")
    print("                              ,,,,,.. ......" + Fore.LIGHTMAGENTA_EX + "&&&" + Fore.RESET + ",......      ")
    print("                              &,,,,.. ................,     ")
    print("                              ,,,,,,...." + Fore.LIGHTMAGENTA_EX + "&&&" + Fore.RESET + "......." + Fore.LIGHTMAGENTA_EX + "&&&" + Fore.RESET + "..     ")
    print("                              ,,,,&#.. ................,    ")
    print("                ,,......,      %,,,,,..................*    ")
    print("        ,,.........." + Fore.LIGHTMAGENTA_EX + "%&&" + Fore.RESET + "...*    &,,,,,**@@&**@@&*/@@(*       ")
    print("      ...." + Fore.LIGHTMAGENTA_EX + ",&&&" + Fore.RESET + ",......." + Fore.LIGHTMAGENTA_EX + "#&&&" + Fore.RESET + ".,   *,,,***************/         ")
    print("      ,......." + Fore.LIGHTMAGENTA_EX + "&&" + Fore.RESET + ".............,                              ")
    print("     ,,,,....," + Fore.LIGHTMAGENTA_EX + "&&/" + Fore.RESET + "........" + Fore.LIGHTMAGENTA_EX + "&&&&" + Fore.RESET + "..*                            ")
    print("     ,,,,,......" + Fore.LIGHTMAGENTA_EX + "&&&" + Fore.RESET + ".............,                           ")
    print("     ,&,&,,,...............,,**/                            ")
    print("      ,,,&,&/..  ....,*****&/*/                             ")
    print("        ,,,,,,,,,************/                              ")
    print("         ,,,,,,,************                                ")
    print("           ,,,,**/&***.                                     ")
    print("            ,,,*,                                           ")